[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
name = "include_dir"
version = "0.6.3-alpha.0"
description = "Embed the contents of a directory in your binary"
license = "MIT"
readme = "../README.md"
keywords = ["assets", "include", "embed", "dir"]
repository = "https://github.com/Michael-F-Bryan/include_dir"
categories = ["development-tools", "web-programming", "game-engines"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges.appveyor]
branch = "master"
repository = "Michael-F-Bryan/include-dir"
service = "github"

[badges.travis-ci]
branch = "master"
repository = "Michael-F-Bryan/include_dir"

[dependencies]
glob = { version = "0.3", optional = true }
include_dir_macros = { version = "0.1.0", path = "../macros" }

[dev-dependencies]
tempdir = "0.3"
